image: mcr.microsoft.com/playwright:v1.49.0

stages:
  - install
  - test
  - report

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npx playwright install --with-deps
    - npm run test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - allure-results/
    reports:
      junit: playwright-report/results.xml

allure:
  stage: report
  script:
    - npm run allure:generate
  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 1 week
